### ISSUE TITLE
drag marker

### ISSUE THREAD

**Issue by smohammedyasin** [capacitor-community/google-maps#124]
how to change marker location by taping or dragging on map. Thank you

**Comment by smohammedyasin** [comment]
seems like this plugin is no more used, and all listening events not working except onMapReady.

**Comment by va2ron1** [comment]
Almost all listeners need to be registered using their respective methods. Check at the [definitions](https://github.com/capacitor-community/capacitor-googlemaps-native/blob/482e140d9f557b0d4a7f05186848b5d95883bd8d/src/definitions.ts#L121)
