### ISSUE TITLE
Maps is not being removed when calling removeMap in iOS

### ISSUE THREAD

**Issue by ynunez** [capacitor-community/google-maps#165]
**Describe the bug**
When using alongside other @capacitor-community/barcode-scanner the map view is visible and displays on top of the camera view. The `removeMap` function is not implemented and therefore the map is always visible behind the webview once initialized.

**To Reproduce**
1. Add @capacitor-community/barcode-scanner and @capacitor-community/google-maps to a project
2. Initialize the map on one page, implement barcode on a separate page

**Expected behavior**
Map view should be closed when calling `removeMap`

**Comment by aanilyildiz** [comment]
Hello, are there any updates on this? I'm having the same issue also.
