### ISSUE TITLE
Analyzing dependencies [!] No podspec found for `CapacitorCommunityGoogleMaps` in `../../node_modules/@capacitor-community/google-maps`

### ISSUE THREAD

**Issue by Arturokin** [capacitor-community/google-maps#180]
**Describe the bug**
Cocoapods throw Analyzing dependencies
[!] No podspec found for `CapacitorCommunityGoogleMaps` in `../../node_modules/@capacitor-community/google-maps`

**To Reproduce**
1. Start a project and install capacitor google maps
2. type 'ionic cap add ios'

**Expected behavior**
Should install cocoapods plugins

**Additional context**
Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.1.5
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.0
   @capacitor/android : 3.5.0
   @capacitor/core    : 3.5.0
   @capacitor/ios     : 3.5.0

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.6.0)   : 1.5.0

System:

   NodeJS : v16.15.0 (/usr/local/bin/node)
   npm    : 8.10.0
   OS     : macOS Big Sur

Cocoapods version: 1.11.3

**Comment by tafelnl** [comment]
Did you run `npx cap sync`?

**Comment by tafelnl** [comment]
Closing because this issue went stale.
