### ISSUE TITLE
Google Maps draws blank on iOS

### ISSUE THREAD

**Issue by alappe** [capacitor-community/google-maps#184]
**Describe the bug**
The rendered map stays completely blank on iOS, works in web.

**To Reproduce**
https://github.com/alappe/capacitor_map_example should show the example. One needs to add an API key with iOS Maps SDK enabled ~~, mine is missing the credit card for now.~~

**Expected behavior**
I'd expect to see a map on iOS.

**Screenshots**
![](https://user-images.githubusercontent.com/1357848/171676132-1a692306-a1da-4dcd-8ec0-479fd804153c.png)

**Additional context**
Tested on a real device, not simulator.

**Comment by tafelnl** [comment]
> iOS Maps SDK enabled, mine is missing the credit card for now

As stated in the docs you need an active billing account. So likely that is what is going wrong here.

**Comment by alappe** [comment]
Thanks tafeln,

since the web version shows me a message that the billing is missing but works fine I asked around in Slack and somebody there told me that the native version should behave exactly the same. I will add billing and then close the issue if this solves it.

**Comment by alappe** [comment]
Adding billing to my account changed the web version to fully functional, whereas the iOS version stays blank. So this was not the issue.

**Comment by alappe** [comment]
That's why I included the minimal code example linked in my issue description.

**Comment by tafelnl** [comment]
I am sorry. I see that now. You are using a different package. You have installed https://www.npmjs.com/package/@capacitor/google-maps instead of https://www.npmjs.com/package/@capacitor-community/google-maps . Those are 2 different packages.
