### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by bstrasburg** [capacitor-community/google-maps#189]
**Describe the bug**
Many times on refresh I get this error

**To Reproduce**
Copy your code from :
https://capacitorjs.com/docs/apis/google-maps#addmarkers

run in web and then refresh the page

**Screenshots**
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/95238855/182561100-48d84b53-f555-484e-9da7-27b2378e11fd.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/95238855/182561159-404c2934-00b0-41b3-aaf2-19eb436e9a3f.png">

**Comment by mujie-dm** [comment]
> **Describe the bug** Many times on refresh I get this error
> 
> **To Reproduce** Copy your code from : https://capacitorjs.com/docs/apis/google-maps#addmarkers
> 
> run in web and then refresh the page
> 
> **Screenshots** <img alt="image" width="1099" src="https://user-images.githubusercontent.com/95238855/182561100-48d84b53-f555-484e-9da7-27b2378e11fd.png">
> 
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/95238855/182561159-404c2934-00b0-41b3-aaf2-19eb436e9a3f.png">

First, please differentiate between '@capacitor-community/capacitor-googlemaps' and '@capacitor/google-maps'.

I was successfully add a marker with @capacitor-community/capacitor-googlemaps.

```
import { CapacitorGoogleMaps } from '@capacitor-community/google-maps';

const mymarker = await CapacitorGoogleMaps.addMarker({
      mapId: document.getElementById("map").getAttribute("data-maps-id"),
      position: {
        latitude: position[0],
        longitude: position[1],
      }, 
      preferences: {
        title: 'My Mark',
        snippet: 'My Location',
      }
    });

//get the marker's ID
  console.log(JSON.parse(JSON.stringify(mymarker))['marker']['markerId']);

```

Regards,
Mujie

**Comment by bstrasburg** [comment]
Im sorry, my issue is with @capacitor/google-maps. Do you know what the difference is between the 2? I might have to switch to the @capacitor-community/capacitor-googlemaps if I keep getting these errors.

**Comment by mujie-dm** [comment]
> Im sorry, my issue is with @capacitor/google-maps. Do you know what the difference is between the 2? I might have to switch to the @capacitor-community/capacitor-googlemaps if I keep getting these errors.

Previously I also used @capacitor/google-maps, but after experiencing some problems, I tried @capacitor-community/capacitor-googlemaps. Maybe you can try it with a simple project first to try this plugin.

Regards,
Mujie

**Comment by tafelnl** [comment]
Thanks @mujie-dm for jumping in and explaining that there is a difference between the two libraries. When I have some time on my hands I will write an explanation on the difference between the two.
