### ISSUE TITLE
This is dead!?!?! does not work

### ISSUE THREAD

**Issue by eomonteiro** [capacitor-community/google-maps#192]
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.android.volley:volley:1.1.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - https://repo.maven.apache.org/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom
       - /android/capacitor-cordova-android-plugins/src/main/libs/volley-1.1.1.jar
       - /android/capacitor-cordova-android-plugins/src/main/libs/volley.jar
       - /android/app/libs/volley-1.1.1.jar
       - /android/app/libs/volley.jar
     Required by:
         project :app > project :capacitor-community-google-maps > com.google.android.libraries.maps:maps:3.1.0-beta

**Comment by tafelnl** [comment]
This project is most certainly not dead. When you have followed all the steps from the docs correctly, it should work. If you have an error, please provide us with a minimal reproduction so we can help you out.

**Comment by lilian131** [comment]
@eomonteiro did you find solution ? I have exactly the same error.
@tafelnl What information do you need ?

**Comment by lilian131** [comment]
on fresh ionic blanc android project:
node: -v: v14.16.0
npm -v: 7.9.0
ionic -v : 6.20.1
@capacitor/core @capacitor/android -v: 4.3.0
Gradle 7.4.2
OS:  Mac OS X 12.1 x86_64

it works on ios

**Comment by tafelnl** [comment]
Capacitor v4 is not yet officially supported. I think it should work fine though.

If you encounter issues, please provide a minimal reproduction, so we can dive into it. Unfortunately, without a reproduction it's nearly impossible to reproduce such an error.

**Comment by lilian131** [comment]
I got it work thanks

**Comment by lilian131** [comment]
I now use this https://capacitorjs.com/docs/apis/google-maps @Dawit114
