### ISSUE TITLE
Snippet is not returned on Web version

### ISSUE THREAD

**Issue by calvinseng** [capacitor-community/google-maps#193]
Snippet doesn't return in the Marker object on web

**To Reproduce**
1. Create the map as usual
2. Fill in the snippet for the market
3. Console.log(marker)
4. Will see that snippet returned is empty

**Expected behavior**
Snippet should be returned

**Comment by tafelnl** [comment]
This repository does not have a web implementation yet. So you wouldn't be able to add a marker on web in the first place. Are you sure you are using this library. Additionally you can keep track of this repo to see when web support will be added.

**Comment by calvinseng** [comment]
> This repository does not have a web implementation yet. So you wouldn't be able to add a marker on web in the first place. Are you sure you are using this library. Additionally you can keep track of this repo to see when web support will be added.

Yes, there's web repository in esm/web.js and it is working in general except for the snippet not being returned.
![Screenshot 2022-08-22 at 9 31 33 AM](https://user-images.githubusercontent.com/12848046/185821875-76483f19-3bb6-455a-8f3d-1e7d38c38f05.png)

**Comment by tafelnl** [comment]
You are most likely using `@capacitor/google-maps`. You are now in the `@capacitor-community/google-maps` repository.
