### ISSUE TITLE
cannot add icon in addMarker

### ISSUE THREAD

**Issue by alihaider1793** [capacitor-community/google-maps#196]
**Describe the bug**
I am using "@capacitor-community/google-maps": "^2.0.0-beta.1". When I try to use the addMarker method, it gives an error saying that icon does not exist in type MarkerPreferences, but it is mentioned in the API documentation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33286510/190244961-8849c7fb-1937-42d2-a7be-54f9b0b80b64.png)

**Comment by wait-matsu** [comment]
Hi

It appears that icons cannot be set for 2.0.0-beta.1.
Instead, the icon is available by specifying the current latest version, 2.0.0-beta.5, as shown below.
```
"dependencies": {
    ...
    "@capacitor-community/google-maps": "git+https://github.com/capacitor-community/google-maps.git#main",
    ...
  },
```

**Comment by alihaider1793** [comment]
Hi, I have another issue, which is not related to this, but I want to use addPolygon and addCircle methods in my code using this plugin. but these plugins are not merged in the main branch right now. How can I use these features?

**Comment by tafelnl** [comment]
It's highly recommended to install the latest version of this repo through NPM (currently `2.0.0-beta.5`). If you want to live on the bleeding edge and want to try out different things, you can install any GitHub repo/branch like so `npm i git+https://github.com/capacitor-community/google-maps.git#main`. Where you can substitute `#main` for any commit/branch/tag.
