### ISSUE TITLE
Marker icon not changing

### ISSUE THREAD

**Issue by IbrahimElkhatib** [capacitor-community/google-maps#201]
**Describe the bug**
I am trying to add a marker with a custom icon from the assets folder, I tried to set the url with: "assets/images/icons/location-pin.png", "../../assets/images/icons/location-pin.png", and "public/assets/images/icons/location-pin.png" with no luck.

**To Reproduce**

```
CapacitorGoogleMaps.addMarker({
          mapId: result.googleMap.mapId,
          position: {
            latitude: this.nearestReader.latitude,
            longitude: this.nearestReader.longitude
          },
          preferences: {
            icon: {
              size: { width: 24, height: 33 },
              url: 'assets/images/icons/location-pin.png',
            },
            snippet: this.nearestReader.readerDescription
          }
        });
```

**Expected behavior**
The marker icon should change to the custom icon instead of the default marker.

**Additional context**

**Error from Xcode debugger console:**
Task <60ED9F6B-1DAF-4912-813E-2C658DF00898>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=assets/images/icons/location-pin.png, NSErrorFailingURLKey=assets/images/icons/location-pin.png, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <60ED9F6B-1DAF-4912-813E-2C658DF00898>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <60ED9F6B-1DAF-4912-813E-2C658DF00898>.<1>, NSUnderlyingError=0x6000029c36c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}

**Comment by LeleuOficial** [comment]
I believe this will solve your problem:

**Comment by elazarza** [comment]
what do you mean actual URL? if I want to use a local assets, the app is runing on capcitor://localhost
and i use capacitor://localhost/assets/image.png/
i get the same error
@tafelnl
