### ISSUE TITLE
when the enable cluster then not see a markers icon 

### ISSUE THREAD

**Issue by Milan-Koladiya** [capacitor-community/google-maps#205]
I am using the capacitor google maps plugin.  so I have added the enable cluster and added multiple markers in the maps
so it is working fine in the web app but when I see the android so I see the only cluster, not the markers

and when I am not using the enable cluster so I see the markers could you please let me know about the issue also I need to add clusters
"await map.enable cluster()"

**Comment by tafelnl** [comment]
You are most likely using `@capacitor/google-maps`. You are now in the `@capacitor-community/google-maps` repository.
