### ISSUE TITLE
Custom HTML marker

### ISSUE THREAD

**Issue by OlivierBeaudet** [capacitor-community/google-maps#206]
Hello,
I'm looking for a solution like the link below for adding custom html markers :

https://developers.google.com/maps/documentation/javascript/advanced-markers/html-markers#maps_advanced_markers_html_simple-typescript

Is there any way to target a marker by CSS and customize it, or add a custom class on it by scripting for doing this ?
Thank you

**Comment by tafelnl** [comment]
You can customize it by changing the icon url. The native libraries do not allow any other type of customization.
