### ISSUE TITLE
Google maps doesn't show HTML objects on ios

### ISSUE THREAD

**Issue by mragwa** [capacitor-community/google-maps#207]
### Plugin(s)
 
@Capacitor/googlemaps
 

### Capacitor Version

```
  @capacitor/cli: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
```

### Platform(s)
IOS 

### Problem
I recently upgraded to capacitor 4 & used @Capacitor/googlemaps instead of capacitor-community/google-maps
It works fine on android devices but i got an issue running it on IOS devices 
it takes all the screen and hide all HTML elements on the page seems like its come over the webview itself.
as shown on the image: 

![image](https://user-images.githubusercontent.com/5574454/206566453-87b90087-ecd8-4cdc-9f8c-68a5d94ab38c.png)

as you can see both header & footer are gone away i searched a lot about that issue but i didn't get any workaround or solution.

also if it will help i got on xcode debug that error direct after map creation :
 
```
2022-12-08 23:36:03.319063+0300 App[3647:1011396] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
```

If you can help with that thank you.

**Comment by tafelnl** [comment]
You are most likely using `@capacitor/google-maps`. You are now in the `@capacitor-community/google-maps` repository.
