### ISSUE TITLE
What about @capacitor/google-maps ?

### ISSUE THREAD

**Issue by rbalet** [capacitor-community/google-maps#208]
**Is your feature request related to a problem? Please describe.**
I'm wondering if I should use this library, or this one https://www.npmjs.com/package/@capacitor/google-maps

**Describe the solution you'd like**
Since the other one is maintained by the capacitor team, it would make sense to use the other one.   
That said, this library seems to have more feature. 

But should this be `deprecated` or are you guys still working on that project ? 

_Sorry if the question does not make sense_

**Comment by tafelnl** [comment]
This library has major benefits over using the official one. The primary benefit being, that _this_ plugin supports overlaying the map element with your webview - and thus custom html elements - on _both_ Android and iOS.

Also, I think it must be said that - although no offense to the also hard-working Capacitor team - but they definitely stole concepts - they even literally copy-pasted source code - from this library without giving credits to the hard work done by the community to create this library. ([source](https://github.com/ionic-team/capacitor-plugins/pull/966))
