### ISSUE TITLE
Localizaiton

### ISSUE THREAD

**Issue by betim** [capacitor-community/google-maps#214]
**Is your feature request related to a problem? Please describe.**
Wouldn't it be great if we could specify a locale?

**Does this feature exist in the Google Maps SDK for android and iOS? Please link the documentation for this feature.**
https://developers.google.com/maps/documentation/javascript/localization

**Describe the solution you'd like**
It can be set on the `GoogleMap.create({locale: ""})`

**Comment by tafelnl** [comment]
This feature does not seem to exist on both the Android and iOS SDK. Therefore it's not possible to implement this. I think google takes care of the localization on these platforms out of the box.
