### ISSUE TITLE
The map generates swipe events when I try to interact with an element above the map.

### ISSUE THREAD

**Issue by oleksandrdevqube** [capacitor-community/google-maps#215]
**Describe the bug**
When I move my finger on the swiper that is above the map, it generates a lot of events, because of this my swiper starts to freeze.

I want to create a slider that will ride on top of the map, but I'm having this problem that I mentioned above.
Perhaps it is worth adding to the map the ability to exclude swipe events, etc.

Modal windows from Ionic also work with freezing.

Can you suggest some other solution to this problem?

It is also worth noting that I am making a version of the program only on Android, so this problem is on this platform.

**Screenshots**
![image](https://user-images.githubusercontent.com/79318359/218278569-11e81b8a-e97a-4326-bf6b-254600d65d81.png)
![image](https://user-images.githubusercontent.com/79318359/218278580-a405759a-2ad5-4fd0-8a50-5c647d57369a.png)

**Comment by tafelnl** [comment]
You are most likely using `@capacitor/google-maps`. You are now in the `@capacitor-community/google-maps` repository.
