### ISSUE TITLE
Icons not supported for iOS

### ISSUE THREAD

**Issue by ngarel** [capacitor-community/google-maps#219]
**Describe the bug**
The documentation mentions the support for icons:
https://capacitor-community.github.io/google-maps/#/api?id=markericon
However there is no implementation for supporting icons on iOS

**Comment by Timileyin105** [comment]
i have same issue for android, checking the documentation i see marker supports icon but in the package icon wasnt provided in the marker preferences

**Comment by tafelnl** [comment]
It _is_ implemented actually, as can be seen in the code:

https://github.com/capacitor-community/google-maps/blob/0381342bb4477192802ae0a1ff292126cf170663/ios/Plugin/Plugin.swift#L234

Are you sure you are not using `@capacitor/google-maps`? You are now in the `@capacitor-community/google-maps` repository.

If you still have problems, please provide a minimal reproduction, so we are able to help you out

**Comment by Timileyin105** [comment]
yes sure @capacitor-community/google-maps

in the android package, icon wasnt provided, both in the markerOption interface and also looking into the com.hemangkumar.capacitorgooglemaps package, setting icon wasn't available in android

**Comment by tafelnl** [comment]
Both `addMarker` and `addMarkers` have a `preferences`:

https://github.com/capacitor-community/google-maps/blob/0381342bb4477192802ae0a1ff292126cf170663/src/interfaces/methods/AddMarkers.ts#L39

https://github.com/capacitor-community/google-maps/blob/0381342bb4477192802ae0a1ff292126cf170663/src/interfaces/methods/AddMarker.ts#L15

Which in turn has `icon` available.

https://github.com/capacitor-community/google-maps/blob/0381342bb4477192802ae0a1ff292126cf170663/src/interfaces/models/GoogleMap/Marker/MarkerPreferences.ts#L69

Without a minimal reproduction I won't be able to help you any further. I'm sorry.

**Comment by Timileyin105** [comment]
hello thanks for your support so far, 
i could see where the issue comes from 
 
i installed it through npm but npm seem to have unupdated code 

check here to see  [link](https://www.npmjs.com/package/@capacitor-community/google-maps?activeTab=code)

**Comment by tafelnl** [comment]
This plugin is officially still in beta. You should install the latest beta by adding `@beta` to your yarn or npm install script. So for example: `npm i @capacitor-community/google-maps@beta`. Otherwise it will install the version with `latest` tag, which is not the latest beta

**Comment by Timileyin105** [comment]
ooh ok, thanks a lot for your support, i appreciate

**Comment by Timileyin105** [comment]
hello @tafelnl ,  i cant seem to  find way to add custom style to marker info window
Please help looking into this
