### ISSUE TITLE
Bug with build on Mac M1

### ISSUE THREAD

**Issue by Aarbel** [capacitor-community/google-maps#223]
Capacitor build fails for iOS build when using google maps plugin with Mac M1.

Using "@capacitor/google-maps": "4.5.0",

```
        ** BUILD FAILED **
        
        
        The following build commands failed:
        SwiftEmitModule normal arm64 Emitting\ module\ for\ CapacitorGoogleMaps (in target 'CapacitorGoogleMaps' from
        project 'Pods')
        SwiftCompile normal arm64 Compiling\ Map.swift
        /Users/clementfradetnormand/Documents/clovis-app/node_modules/@capacitor/google-maps/ios/Plugin/Map.swift (in
        target 'CapacitorGoogleMaps' from project 'Pods')
        (2 failures)
````

Looks it had been solved but not yet implemented: https://forum.ionicframework.com/t/google-maps-capacitor-not-working-on-ios/223525/14

Do you have any tricks to solve this problem ? 

Thanks for your help

**Comment by Aarbel** [comment]
Cf https://github.com/ionic-team/capacitor/issues/5838

**Comment by Aarbel** [comment]
Cf https://github.com/googlemaps/google-maps-ios-utils/issues/355

**Comment by tafelnl** [comment]
You are most likely using `@capacitor/google-maps`. You are now in the `@capacitor-community/google-maps` repository.
