### ISSUE TITLE
Not compatible with @capacitor/core 6.0.0

### ISSUE THREAD

**Issue by ravimittal16** [capacitor-community/google-maps#233]
**NPM Error**
Your version of @capacitor/google-maps is not compatible with @capacitor/core 6.0.0..

**To Reproduce**
1. Go to IONIC Upgrade
2. Click on 'Migrate to Capacitor 6'
3. Scroll down to 'Output Window on VS Code'

**Expected behavior**
Should upgrade to Capacitor 6 without any issues

![image](https://github.com/capacitor-community/google-maps/assets/1586169/583f3c94-c493-4f1a-9cad-381fbde3922f)

**Comment by twatoris** [comment]
Well, this has taken somewhat longer to resolve than I hoped. Obviously, @capacitor/google-maps has not been updated to support the new @capacitor/core@6.0.0. Currently using  --legacy-peer-deps flag to bypass the peer dependency conflict, pending when the upgrade for @capacitor/google-maps would be available. The only other option, interim, would be to defer/downgrade from @capacitor/core@6.0.0.

**Comment by frederikheld** [comment]
I got it working with Capacitor 6 by installing the ACTUAL latest version of this plugin. See: https://github.com/capacitor-community/google-maps/discussions/234

**Comment by frederikheld** [comment]
@ravimittal16 I read your error message again and noticed that you are in the wrong repo. The error is about `@capacitor/google-maps`, but this is the repo for `@capacitor-community/google-maps`.

**Comment by paulnagle** [comment]
For anyone looking for info on the ionic team's @capacitor/google-maps v6 compatibilty issues, the answer is here
https://github.com/ionic-team/capacitor-google-maps/issues/5#issuecomment-2072345149

**Comment by ravimittal16** [comment]
@frederikheld I think they are same.

**Comment by ravimittal16** [comment]
We were able to update Capacitor v6 with RC version of google-maps plugin. Hence clsoing the issue

**Comment by frederikheld** [comment]
They are definitely not the same. I spent a lot of weeks recently, to figure out how both of them work and they work very different (and none of them properly)
