### ISSUE TITLE
Drawings on the map: Tiles

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/google-maps#3]

**Comment by rpsoftech** [comment]
@hemangsk I would like to help you with this feature in android

**Comment by hemangsk** [comment]
@rpsoftech Thanks! That sounds really great!

**Comment by rpsoftech** [comment]
@hemangsk  Can You Please Explain The Requirement??

What Exactly We need To Achieve Here

**Comment by hemangsk** [comment]
Hey @rpsoftech, Current state of the package is that users can draw a shape (circle, polyline, polygon) but they cannot customise it with borders and colors. There's an issue for that https://github.com/hemangsk/capacitor-googlemaps-native/issues/11.  

This issue for "Tiles" corresponds to "Tile layer" at https://developers.google.com/maps/documentation/ios-sdk/tiles, so that users can take an Image / Tile and overlap it on their existing map by passing a coordinate and zoom level.

So, what do you think will be more interesting/useful for you to work on, [colors and borders on shapes](https://github.com/hemangsk/capacitor-googlemaps-native/issues/11)  or this Tiles one?

**Comment by rpsoftech** [comment]
> Hey @rpsoftech, Current state of the package is that users can draw a shape (circle, polyline, polygon) but they cannot customise it with borders and colors. There's an issue for that #11.
> 
> This issue for "Tiles" corresponds to "Tile layer" at https://developers.google.com/maps/documentation/ios-sdk/tiles, so that users can take an Image / Tile and overlap it on their existing map by passing a coordinate and zoom level.
> 
> So, what do you think will be more interesting/useful for you to work on, [colors and borders on shapes](https://github.com/hemangsk/capacitor-googlemaps-native/issues/11) or this Tiles one?

I would love to work on colours and borders first.
After successful implementation of that.
We will look for tiles one..

**Comment by hemangsk** [comment]
Sounds awesome! Thanks

**Comment by tafelnl** [comment]
Closing this issue in favor of #157
